"""Core trade domain objects — enums, signals, results, active trades."""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from typing import Optional


class TradeStatus(str, Enum):
    """Lifecycle status of a trade."""
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    WON = "WON"
    LOST = "LOST"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class TradeDirection(str, Enum):
    """Direction + option type combination."""
    BUY_CALL = "BUY_CALL"
    BUY_PUT = "BUY_PUT"
    SELL_CALL = "SELL_CALL"
    SELL_PUT = "SELL_PUT"

    @property
    def option_type(self) -> str:
        return "CE" if "CALL" in self.value else "PE"

    @property
    def is_buying(self) -> bool:
        return self.value.startswith("BUY")


@dataclass
class TradeSignal:
    """Signal generated by a strategy before trade creation."""
    direction: str              # e.g. "BUY_CALL", "BUY_PUT"
    strike: int
    option_type: str            # "CE" or "PE"
    entry_premium: float
    sl_premium: float
    target_premium: float
    confidence: float
    verdict: str
    spot_price: float
    timestamp: datetime = field(default_factory=datetime.now)
    strategy_name: Optional[str] = None
    reasoning: Optional[str] = None

    def to_dict(self) -> dict:
        d = asdict(self)
        d["timestamp"] = self.timestamp.isoformat()
        return d

    @classmethod
    def from_dict(cls, d: dict) -> TradeSignal:
        d = dict(d)  # shallow copy
        ts = d.get("timestamp")
        if isinstance(ts, str):
            d["timestamp"] = datetime.fromisoformat(ts)
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class TradeResult:
    """Outcome of a resolved trade."""
    action: str                 # "WON", "LOST", "EXPIRED", "CANCELLED"
    pnl: float                  # profit/loss percentage
    reason: str                 # exit reason string
    exit_premium: float
    trade_id: int
    tracker_type: str           # "iron_pulse", "selling", "dessert", etc.

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> TradeResult:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class ActiveTrade:
    """An active trade being monitored (mirrors premium_monitor.ActiveTrade)."""
    trade_id: int
    tracker_type: str           # "iron_pulse", "selling", "dessert", "momentum", etc.
    strike: int
    option_type: str            # "CE" or "PE"
    instrument_token: int
    entry_premium: float
    sl_premium: float
    target_premium: float
    is_selling: bool = False

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> ActiveTrade:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    @classmethod
    def from_db_row(cls, row: dict, tracker_type: str, instrument_token: int = 0,
                    is_selling: bool = False) -> ActiveTrade:
        """Build from a database row dict (sqlite3.Row or plain dict)."""
        return cls(
            trade_id=row["id"],
            tracker_type=tracker_type,
            strike=row["strike"],
            option_type=row["option_type"],
            instrument_token=instrument_token,
            entry_premium=row["entry_premium"],
            sl_premium=row["sl_premium"],
            target_premium=row.get("target_premium", row.get("target1_premium", 0)),
            is_selling=is_selling,
        )
