"""initial tables

Revision ID: 836c92a9ed66
Revises: 
Create Date: 2026-02-24 19:25:46.530237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836c92a9ed66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=False),
    sa.Column('atm_strike', sa.Integer(), nullable=False),
    sa.Column('total_call_oi', sa.Integer(), nullable=False),
    sa.Column('total_put_oi', sa.Integer(), nullable=False),
    sa.Column('call_oi_change', sa.Integer(), nullable=False),
    sa.Column('put_oi_change', sa.Integer(), nullable=False),
    sa.Column('atm_call_oi_change', sa.Integer(), nullable=False),
    sa.Column('atm_put_oi_change', sa.Integer(), nullable=False),
    sa.Column('itm_call_oi_change', sa.Integer(), nullable=False),
    sa.Column('itm_put_oi_change', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('prev_verdict', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('vix', sa.Float(), nullable=False),
    sa.Column('iv_skew', sa.Float(), nullable=False),
    sa.Column('max_pain', sa.Integer(), nullable=False),
    sa.Column('signal_confidence', sa.Float(), nullable=False),
    sa.Column('futures_oi', sa.Integer(), nullable=False),
    sa.Column('futures_oi_change', sa.Integer(), nullable=False),
    sa.Column('futures_basis', sa.Float(), nullable=False),
    sa.Column('analysis_blob', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_history_timestamp', 'analysis_history', ['timestamp'], unique=False)
    op.create_table('dessert_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('target_premium', sa.Float(), nullable=False),
    sa.Column('iv_skew_at_creation', sa.Float(), nullable=True),
    sa.Column('vix_at_creation', sa.Float(), nullable=True),
    sa.Column('max_pain_at_creation', sa.Float(), nullable=True),
    sa.Column('spot_move_30m', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strike', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('sl_premium', sa.Float(), nullable=False),
    sa.Column('spot_at_creation', sa.Float(), nullable=False),
    sa.Column('verdict_at_creation', sa.String(), nullable=False),
    sa.Column('signal_confidence', sa.Float(), nullable=True),
    sa.Column('iv_at_creation', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_premium', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('profit_loss_pct', sa.Float(), nullable=True),
    sa.Column('max_premium_reached', sa.Float(), nullable=True),
    sa.Column('min_premium_reached', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_premium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dessert_created', 'dessert_trades', ['created_at'], unique=False)
    op.create_index('ix_dessert_status', 'dessert_trades', ['status'], unique=False)
    op.create_table('iron_pulse_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneyness', sa.String(), nullable=False),
    sa.Column('target1_premium', sa.Float(), nullable=False),
    sa.Column('target2_premium', sa.Float(), nullable=True),
    sa.Column('risk_pct', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activation_premium', sa.Float(), nullable=True),
    sa.Column('hit_sl', sa.Boolean(), nullable=False),
    sa.Column('hit_target', sa.Boolean(), nullable=False),
    sa.Column('profit_loss_points', sa.Float(), nullable=True),
    sa.Column('t1_hit', sa.Boolean(), nullable=False),
    sa.Column('t1_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('t1_premium', sa.Float(), nullable=True),
    sa.Column('peak_premium', sa.Float(), nullable=True),
    sa.Column('trailing_sl', sa.Float(), nullable=True),
    sa.Column('call_oi_change_at_creation', sa.Float(), nullable=False),
    sa.Column('put_oi_change_at_creation', sa.Float(), nullable=False),
    sa.Column('pcr_at_creation', sa.Float(), nullable=False),
    sa.Column('max_pain_at_creation', sa.Integer(), nullable=False),
    sa.Column('support_at_creation', sa.Integer(), nullable=False),
    sa.Column('resistance_at_creation', sa.Integer(), nullable=False),
    sa.Column('trade_reasoning', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strike', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('sl_premium', sa.Float(), nullable=False),
    sa.Column('spot_at_creation', sa.Float(), nullable=False),
    sa.Column('verdict_at_creation', sa.String(), nullable=False),
    sa.Column('signal_confidence', sa.Float(), nullable=True),
    sa.Column('iv_at_creation', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_premium', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('profit_loss_pct', sa.Float(), nullable=True),
    sa.Column('max_premium_reached', sa.Float(), nullable=True),
    sa.Column('min_premium_reached', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_premium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iron_pulse_created', 'iron_pulse_trades', ['created_at'], unique=False)
    op.create_index('ix_iron_pulse_status', 'iron_pulse_trades', ['status'], unique=False)
    op.create_table('momentum_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('target_premium', sa.Float(), nullable=False),
    sa.Column('iv_skew_at_creation', sa.Float(), nullable=True),
    sa.Column('vix_at_creation', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('confirmation_status', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strike', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('sl_premium', sa.Float(), nullable=False),
    sa.Column('spot_at_creation', sa.Float(), nullable=False),
    sa.Column('verdict_at_creation', sa.String(), nullable=False),
    sa.Column('signal_confidence', sa.Float(), nullable=True),
    sa.Column('iv_at_creation', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_premium', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('profit_loss_pct', sa.Float(), nullable=True),
    sa.Column('max_premium_reached', sa.Float(), nullable=True),
    sa.Column('min_premium_reached', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_premium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_momentum_created', 'momentum_trades', ['created_at'], unique=False)
    op.create_index('ix_momentum_status', 'momentum_trades', ['status'], unique=False)
    op.create_table('oi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=False),
    sa.Column('strike_price', sa.Integer(), nullable=False),
    sa.Column('ce_oi', sa.Integer(), nullable=False),
    sa.Column('ce_oi_change', sa.Integer(), nullable=False),
    sa.Column('pe_oi', sa.Integer(), nullable=False),
    sa.Column('pe_oi_change', sa.Integer(), nullable=False),
    sa.Column('ce_volume', sa.Integer(), nullable=False),
    sa.Column('pe_volume', sa.Integer(), nullable=False),
    sa.Column('ce_iv', sa.Float(), nullable=False),
    sa.Column('pe_iv', sa.Float(), nullable=False),
    sa.Column('ce_ltp', sa.Float(), nullable=False),
    sa.Column('pe_ltp', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oi_snapshots_timestamp', 'oi_snapshots', ['timestamp'], unique=False)
    op.create_index('ix_oi_snapshots_ts_strike', 'oi_snapshots', ['timestamp', 'strike_price'], unique=False)
    op.create_table('selling_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_premium', sa.Float(), nullable=False),
    sa.Column('target2_premium', sa.Float(), nullable=True),
    sa.Column('t1_hit', sa.Boolean(), nullable=False),
    sa.Column('t1_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strike', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(), nullable=False),
    sa.Column('entry_premium', sa.Float(), nullable=False),
    sa.Column('sl_premium', sa.Float(), nullable=False),
    sa.Column('spot_at_creation', sa.Float(), nullable=False),
    sa.Column('verdict_at_creation', sa.String(), nullable=False),
    sa.Column('signal_confidence', sa.Float(), nullable=True),
    sa.Column('iv_at_creation', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_premium', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('profit_loss_pct', sa.Float(), nullable=True),
    sa.Column('max_premium_reached', sa.Float(), nullable=True),
    sa.Column('min_premium_reached', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_premium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_selling_created', 'selling_trades', ['created_at'], unique=False)
    op.create_index('ix_selling_status', 'selling_trades', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_logs_component', 'system_logs', ['component'], unique=False)
    op.create_index('ix_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('ix_system_logs_timestamp', 'system_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_logs_timestamp', table_name='system_logs')
    op.drop_index('ix_system_logs_level', table_name='system_logs')
    op.drop_index('ix_system_logs_component', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('settings')
    op.drop_index('ix_selling_status', table_name='selling_trades')
    op.drop_index('ix_selling_created', table_name='selling_trades')
    op.drop_table('selling_trades')
    op.drop_index('ix_oi_snapshots_ts_strike', table_name='oi_snapshots')
    op.drop_index('ix_oi_snapshots_timestamp', table_name='oi_snapshots')
    op.drop_table('oi_snapshots')
    op.drop_index('ix_momentum_status', table_name='momentum_trades')
    op.drop_index('ix_momentum_created', table_name='momentum_trades')
    op.drop_table('momentum_trades')
    op.drop_index('ix_iron_pulse_status', table_name='iron_pulse_trades')
    op.drop_index('ix_iron_pulse_created', table_name='iron_pulse_trades')
    op.drop_table('iron_pulse_trades')
    op.drop_index('ix_dessert_status', table_name='dessert_trades')
    op.drop_index('ix_dessert_created', table_name='dessert_trades')
    op.drop_table('dessert_trades')
    op.drop_index('ix_analysis_history_timestamp', table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
